import type { Member, Offer, Request } from "./types";

const iso = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86_400_000).toISOString();

export const demoMembers: Member[] = [
  {
    id: "m_giulia",
    wildapricot_contact_id: "WA-48210",
    name: "Giulia Ferrari",
    email: "giulia@tenutaferrari.it",
    phone: "+39 051 220 118",
    company: "Tenuta Ferrari S.r.l.",
    title: "Export Director",
    industry: "Food & Beverage",
    geography: "Emilia-Romagna, Italy",
    bio: "Third-generation producer of DOP balsamic vinegar and artisanal preserves. Building a long-term presence in the North American specialty retail channel.",
    membership_level: "Corporate Member",
    membership_status: "active",
    role: "member",
    matching_enabled: true,
    last_synced_at: iso(0),
    avatar_initials: "GF",
  },
  {
    id: "m_marcus",
    wildapricot_contact_id: "WA-51877",
    name: "Marcus Bell",
    email: "marcus@goldenstatefinefoods.com",
    phone: "+1 415 555 0142",
    company: "Golden State Fine Foods",
    title: "Managing Partner",
    industry: "Food & Beverage",
    geography: "California, United States",
    bio: "Importer and distributor supplying 340+ independent grocers and restaurant groups across California with authentic European specialty foods.",
    membership_level: "Corporate Member",
    membership_status: "active",
    role: "member",
    matching_enabled: true,
    last_synced_at: iso(0),
    avatar_initials: "MB",
  },
  {
    id: "m_elena",
    wildapricot_contact_id: "WA-49004",
    name: "Elena Rossi",
    email: "elena@rossibrand.it",
    company: "Rossi Brand Studio",
    title: "Founder",
    industry: "Design & Marketing",
    geography: "Milan, Italy",
    bio: "Packaging and brand systems for food and beverage exporters entering regulated markets.",
    membership_level: "Professional Member",
    membership_status: "active",
    role: "member",
    matching_enabled: true,
    last_synced_at: iso(1),
    avatar_initials: "ER",
  },
  {
    id: "m_dana",
    wildapricot_contact_id: "WA-52310",
    name: "Dana Whitcomb",
    email: "dana@pacificgatelogistics.com",
    company: "Pacific Gate Logistics",
    title: "Director of Trade Compliance",
    industry: "Logistics & Trade",
    geography: "San Francisco Bay Area, United States",
    bio: "Licensed customs brokerage and cold-chain freight forwarding for EU-to-US food importers.",
    membership_level: "Corporate Member",
    membership_status: "active",
    role: "member",
    matching_enabled: true,
    last_synced_at: iso(2),
    avatar_initials: "DW",
  },
  {
    id: "m_paolo",
    wildapricot_contact_id: "WA-44120",
    name: "Paolo Bianchi",
    email: "paolo@cantinabianchi.it",
    company: "Cantina Bianchi",
    title: "Owner",
    industry: "Food & Beverage",
    geography: "Veneto, Italy",
    bio: "Family winery producing Valpolicella and Amarone for the on-trade channel.",
    membership_level: "Corporate Member",
    membership_status: "lapsed",
    role: "member",
    matching_enabled: false,
    last_synced_at: iso(9),
    avatar_initials: "PB",
  },
  {
    id: "m_sofia",
    wildapricot_contact_id: "WA-10001",
    name: "Sofia Conti",
    email: "sofia@italiancommerce.org",
    company: "Italian Commerce Association",
    title: "Membership Director",
    industry: "Association",
    geography: "New York, United States",
    bio: "Administers member services and business development programs for the association.",
    membership_level: "Staff",
    membership_status: "active",
    role: "admin",
    matching_enabled: true,
    last_synced_at: iso(0),
    avatar_initials: "SC",
  },
];

export const demoOffers: Offer[] = [
  {
    kind: "offer",
    id: "of_ferrari_dop",
    member_id: "m_giulia",
    title: "DOP balsamic vinegar and artisanal preserves for import",
    description:
      "Certified DOP balsamic vinegar of Modena, aged 12 and 25 years, plus a line of artisanal fruit preserves and truffle condiments. Export-ready: FDA registered facility, bilingual labelling, EU organic certification, container and mixed-pallet volumes. Seeking distribution partners rather than one-off wholesale orders.",
    category: "Specialty food supply",
    industry: "Food & Beverage",
    geography: "Italy — exporting to North America",
    product_service: "product",
    audience: "b2b",
    keywords: ["balsamic", "DOP", "specialty food", "import", "export", "distribution", "italian"],
    status: "active",
    created_at: iso(41),
    updated_at: iso(6),
    embedding: null,
  },
  {
    kind: "offer",
    id: "of_gsff_distribution",
    member_id: "m_marcus",
    title: "California specialty grocery distribution network",
    description:
      "Statewide distribution for imported specialty food brands: 340+ independent grocers, gourmet retail chains and restaurant groups across California. We handle warehousing, temperature-controlled logistics, retailer onboarding, in-store demos and category management for European producers entering the US market.",
    category: "Distribution & channel access",
    industry: "Food & Beverage",
    geography: "California, United States",
    product_service: "service",
    audience: "b2b",
    keywords: ["distribution", "california", "specialty food", "retail", "import", "grocery"],
    status: "active",
    created_at: iso(60),
    updated_at: iso(4),
    embedding: null,
  },
  {
    kind: "offer",
    id: "of_rossi_packaging",
    member_id: "m_elena",
    title: "Export packaging and label compliance design",
    description:
      "Brand and packaging systems for Italian food producers entering the United States, including FDA-compliant label architecture, nutrition panel typesetting and shelf-impact design for specialty retail.",
    category: "Brand & packaging design",
    industry: "Design & Marketing",
    geography: "Italy — serving EU and US markets",
    product_service: "service",
    audience: "b2b",
    keywords: ["packaging", "label", "compliance", "branding", "specialty food", "export"],
    status: "active",
    created_at: iso(75),
    updated_at: iso(20),
    embedding: null,
  },
  {
    kind: "offer",
    id: "of_pacific_customs",
    member_id: "m_dana",
    title: "US customs brokerage and cold-chain import handling",
    description:
      "Licensed customs brokerage for EU food importers: FDA prior notice filing, FSVP support, port clearance at Oakland and Long Beach, bonded warehousing and temperature-controlled drayage to distributor DCs.",
    category: "Logistics & compliance",
    industry: "Logistics & Trade",
    geography: "California, United States",
    product_service: "service",
    audience: "b2b",
    keywords: ["customs", "import", "logistics", "FDA", "cold chain", "california"],
    status: "active",
    created_at: iso(88),
    updated_at: iso(11),
    embedding: null,
  },
  {
    kind: "offer",
    id: "of_bianchi_wine",
    member_id: "m_paolo",
    title: "Valpolicella and Amarone for US on-trade",
    description:
      "Estate-bottled Valpolicella Superiore and Amarone della Valpolicella available for import in mixed pallets, with allocation for restaurant and wine-bar programs.",
    category: "Specialty beverage supply",
    industry: "Food & Beverage",
    geography: "Veneto, Italy",
    product_service: "product",
    audience: "b2b",
    keywords: ["wine", "amarone", "import", "italian", "distribution"],
    status: "active",
    created_at: iso(130),
    updated_at: iso(120),
    embedding: null,
  },
];

export const demoRequests: Request[] = [
  {
    kind: "request",
    id: "rq_ferrari_distributor",
    member_id: "m_giulia",
    title: "Seeking a California distributor for Italian specialty food",
    description:
      "We are looking for an established specialty food distributor in California with existing relationships in independent grocery and gourmet retail. Priority is a partner able to import directly, warehouse temperature-sensitive product and run retailer onboarding for an Italian DOP condiment line. Long-term exclusive arrangement preferred over spot wholesale.",
    category: "Distribution & channel access",
    industry: "Food & Beverage",
    geography: "California, United States",
    product_service: "service",
    audience: "b2b",
    keywords: ["distribution", "california", "specialty food", "retail", "import", "italian"],
    status: "active",
    created_at: iso(30),
    updated_at: iso(5),
    expires_at: new Date(Date.now() + 90 * 86_400_000).toISOString(),
    embedding: null,
  },
  {
    kind: "request",
    id: "rq_gsff_producers",
    member_id: "m_marcus",
    title: "Seeking Italian producers of DOP condiments and preserves",
    description:
      "Expanding our Italian import portfolio for 2027. Looking for certified Italian producers of DOP balsamic vinegar, artisanal preserves and truffle condiments with export-ready certification and the capacity for consistent container volumes. Producers seeking a long-term distribution partnership are the best fit.",
    category: "Specialty food supply",
    industry: "Food & Beverage",
    geography: "Italy",
    product_service: "product",
    audience: "b2b",
    keywords: ["italian", "DOP", "balsamic", "specialty food", "import", "export", "preserves"],
    status: "active",
    created_at: iso(22),
    updated_at: iso(3),
    expires_at: null,
    embedding: null,
  },
  {
    kind: "request",
    id: "rq_ferrari_customs",
    member_id: "m_giulia",
    title: "US customs and FDA compliance support for food import",
    description:
      "Need a licensed customs partner to handle FDA prior notice, FSVP requirements and cold-chain drayage for shipments arriving at West Coast ports.",
    category: "Logistics & compliance",
    industry: "Logistics & Trade",
    geography: "California, United States",
    product_service: "service",
    audience: "b2b",
    keywords: ["customs", "FDA", "import", "logistics", "cold chain"],
    status: "active",
    created_at: iso(14),
    updated_at: iso(14),
    expires_at: null,
    embedding: null,
  },
  {
    kind: "request",
    id: "rq_gsff_packaging",
    member_id: "m_marcus",
    title: "Label redesign partner for US market compliance",
    description:
      "Looking for a design studio that can adapt European packaging and labels for US retail shelves, including compliant nutrition panels for the brands we import.",
    category: "Brand & packaging design",
    industry: "Design & Marketing",
    geography: "Italy or United States",
    product_service: "service",
    audience: "b2b",
    keywords: ["packaging", "label", "compliance", "branding", "retail"],
    status: "active",
    created_at: iso(48),
    updated_at: iso(35),
    expires_at: null,
    embedding: null,
  },
];
