/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as ActivateCompleteRouteImport } from './routes/activate-complete'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ApiBootstrapSyncRouteImport } from './routes/api/bootstrap-sync'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ApiPublicWildapricotWebhookRouteImport } from './routes/api/public/wildapricot/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateCompleteRoute = ActivateCompleteRouteImport.update({
  id: '/activate-complete',
  path: '/activate-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapSyncRoute = ApiBootstrapSyncRouteImport.update({
  id: '/api/bootstrap-sync',
  path: '/api/bootstrap-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const ApiPublicWildapricotWebhookRoute =
  ApiPublicWildapricotWebhookRouteImport.update({
    id: '/api/public/wildapricot/webhook',
    path: '/api/public/wildapricot/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-complete': typeof ActivateCompleteRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/api/bootstrap-sync': typeof ApiBootstrapSyncRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/public/wildapricot/webhook': typeof ApiPublicWildapricotWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-complete': typeof ActivateCompleteRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/api/bootstrap-sync': typeof ApiBootstrapSyncRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/matches': typeof MatchesIndexRoute
  '/api/public/wildapricot/webhook': typeof ApiPublicWildapricotWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-complete': typeof ActivateCompleteRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/api/bootstrap-sync': typeof ApiBootstrapSyncRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/public/wildapricot/webhook': typeof ApiPublicWildapricotWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/activate-complete'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/notifications'
    | '/offers'
    | '/profile'
    | '/requests'
    | '/api/bootstrap-sync'
    | '/matches/$matchId'
    | '/matches/'
    | '/api/public/wildapricot/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/activate-complete'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/offers'
    | '/profile'
    | '/requests'
    | '/api/bootstrap-sync'
    | '/matches/$matchId'
    | '/matches'
    | '/api/public/wildapricot/webhook'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/activate-complete'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/notifications'
    | '/offers'
    | '/profile'
    | '/requests'
    | '/api/bootstrap-sync'
    | '/matches/$matchId'
    | '/matches/'
    | '/api/public/wildapricot/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  ActivateCompleteRoute: typeof ActivateCompleteRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  RequestsRoute: typeof RequestsRoute
  ApiBootstrapSyncRoute: typeof ApiBootstrapSyncRoute
  ApiPublicWildapricotWebhookRoute: typeof ApiPublicWildapricotWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-complete': {
      id: '/activate-complete'
      path: '/activate-complete'
      fullPath: '/activate-complete'
      preLoaderRoute: typeof ActivateCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-sync': {
      id: '/api/bootstrap-sync'
      path: '/api/bootstrap-sync'
      fullPath: '/api/bootstrap-sync'
      preLoaderRoute: typeof ApiBootstrapSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/api/public/wildapricot/webhook': {
      id: '/api/public/wildapricot/webhook'
      path: '/api/public/wildapricot/webhook'
      fullPath: '/api/public/wildapricot/webhook'
      preLoaderRoute: typeof ApiPublicWildapricotWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  ActivateCompleteRoute: ActivateCompleteRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  MatchesRoute: MatchesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  RequestsRoute: RequestsRoute,
  ApiBootstrapSyncRoute: ApiBootstrapSyncRoute,
  ApiPublicWildapricotWebhookRoute: ApiPublicWildapricotWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
